version: '3'
networks: 
   app-tier-traccar: 
      driver: bridge 
services: 

 mysql:
  image: mysql
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  hostname: mysql
  environment:
   - MYSQL_DATABASE=tc
   - MYSQL_USER=tc
   - MYSQL_PASSWORD=Roadland98709870! 
   - MYSQL_ROOT_PASSWORD=Roadland98709870!
  volumes:
   - /opt/traccar/mysql-data:/var/lib/mysql
  ports:
   - "3306:3306"
  networks:
   - app-tier-traccar

 traccar:
  image: traccar/traccar:latest
  hostname: traccar
  restart: always
  ports:
   - "5000-5150:5000-5150"
   - "8082:8082"
  networks:
   - app-tier-traccar
  volumes:
   - ./conf/traccar.xml:/opt/traccar/conf/traccar.xml
  depends_on:
   - mysql

volumes:
   mysql-data:
